---

fake_backend_source_repo: "git@github.com:juliencoste/fake-backend.git"
fake_backend_source_branch: "master"

fake_backend_docker_image_tag: "v1"

home: "/home/centos"

#secret data vaulted
github_private_key: "{{ vault_github_private_key }}"
docker_hub_login: "{{ vault_docker_hub_login }}"
docker_hub_email: "{{ vault_docker_hub_email }}"
docker_hub_password: "{{ vault_docker_hub_password }}"
